#+OPTIONS: toc:nil

#+TITLE: Comparison Theory

* Self Adjoint \(A\)

For the following applications it is sufficient to restrict to the case where \(A\) is self adjoint. Let's ju
st take a look at this condition. That is, an endomorphism \(T\) is self adjoint provided \(g(T(X), Y) = g(X, T(Y)\).

Given any arbitrary endomorphism \(T\), the adjoint \(T^{\ast}\) is defined by the relation
\[
g(T^{\ast} (X), Y) = g(X, T(Y)).
\]
The operator \(T\) is then self adjoint if and only if \(T = T^{\ast}\).

Equivalently, \(T^{\ast}\) is defined by metric contraction: let \(B(X, Y) = g(X, T(Y)) = \operatorname{Tr}_g^2 T\) where the \(2\) denotes the contraction is in the second slot of \(g\). Then \(T^{\ast} = \operatorname{Tr}_{g^{\ast}}^1 B\) where \(g^{\ast}\) denotes the dual metric. In other words, \(T^{\ast}\) is obtained by first metric lowering the upper index of \(T\) into the second slot and then metric-raising the first slot. Explicitly,
\[
T^{\ast} = \operatorname{Tr}^1 g^{\ast} \otimes \operatorname{Tr}^2 (g \otimes T).
\]
With respect to a frame,
\[
(T^{\ast})^i_j = g^{ik} g_{jl} T^l_k
\]
In particular, if \(T_t\) is a smooth one parameter family along \(\gamma\), since \(g\) is also smooth, then \(T^{\ast}_t\) is a smooth one-parameter family.

#+BEGIN_lem
For any tangent vector \(Z\), the endomorphism \(\operatorname{R}_Z\) is \(g\)-self adjoint. That is for any vector fields \(X, Y\) along \(\gamma\),
\[
g(\operatorname{R}_Z (X), Y) = g(X, \operatorname{R}_Z(Y)).
\]
#+END_lem

#+BEGIN_proof
By the curvature tensor symmetries,
\[
g(\operatorname{R}_Z (X), Y) = \operatorname{Rm} (X, Z, Z, Y) = \operatorname{Rm} (Y, Z, Z, X) = g(X, \operatorname{R}_Z (Y))
\]
so that \(\operatorname{R}_Z\) is self adjoint.
#+END_proof

Employing the Riccati equation and the self-adjointness of \(\operatorname{R}_V\) we may deduce necessary and sufficient conditions for when \(A(t)\) is self adjoint for each \(t\).

#+BEGIN_lem
Let \(A(t)\) satisfy the Riccati equation. The \(A(t)\) is self adjoint for every \(t\) if and only if \(A(0)\) is self adjoint.
#+END_lem

#+BEGIN_proof
One implication is obvious: if \(A(t)\) is self adjoint for every \(t\), then certainly it is self adjoint for \(t = 0\).

Conversely, suppose that \(A(0)\) is self adjoint. Let \(A^{\ast}\) denote it's adjoint. That is \(A^{\ast}\) is defined by
\[
g(A^{\ast} (X), Y) = g(X, A(Y))
\]
and is differentiable with respect to \(t\). By assumption \(A^{\ast}(0) = A\) and we need to show that \(A^{\ast}(t) = A(t)\) for every \(t\).

Now, we determine \(A^{\ast} (t)\) and \(\partial_t A^{\ast} (t)\) by their action on tangent vectors at \(\gamma(t)\). In fact, we may do this by determining their action on parallel fields along \(\gamma\): Let \(X, Y\) be arbitrary parallel vector fields along \(\gamma\). Since parallel transport is an isomorphism, every tangent vector in \(T_{\gamma(t)} M\) is equal to the restriction \(X(t)\) of such a parallel field \(X\) along \(\gamma\). Thus we may compute the variation of \(A^{\ast}\) by differentiating the relation
\[
g(A^{\ast} (X), Y) = g(X, A(Y)).
\]
where \(X, Y\) and parallel vector fields. As usual, putting \(V = \gamma'\) then differentiating, using metric compatibility and the fact that \(X, Y\) are parallel gives
\[
g((\nabla_V A^{\ast}) (X), Y) = g(X, (\nabla_V A) (Y)).
\]
Note here that the parallel assumption gives \(\nabla_V X = \nabla_V Y = 0\) and \(\nabla_V [A(X)] = (\nabla_V A) (X) + A(\nabla_V X) = (\nabla_V A)(X)\).

Therefore from the Riccati equation and the fact that \(\operatorname{R}_V\) is self adjoint,
\[
g((\nabla_V A^{\ast}) (X), Y) = -g(X, \operatorname{R}_V (Y)) - g(X, A^2(Y)) = -g(\operatorname{R}_V (X) + (A^{\ast})^2 (X), Y).
\]
That is, for every \(X, Y\)
\[
g((\nabla_V A^{\ast})(X) + (A^{\ast})^2 (X) + \operatorname{R}_V (X), Y) = 0
\]
and hence
\[
\nabla_V A^{\ast} + (A^{\ast})^2 + \operatorname{R}_V = 0.
\]

Therefore the adjoint \(A^{\ast}\) also satisfies the Riccati equation! But if \(A(0)\) is self adjoint, then \(A^{\ast}(0) = A(0)\) and we see that \(A^{\ast}\) satisfies the Riccati equation with the same initial conditions as \(A\). Hence by uniqueness of solutions, \(A^{\ast} = A\) and therefore \(A\) is self adjoint.
#+END_proof

#+BEGIN_rem
Ensuring that \(A\) is self adjoint thus amounts to choosing self-adjoint initial conditions \(A(0)\) or equivalently, choosing \(J_i(0), J_i'(0)\), \(1 \leq i \leq n\) such that the mapping \(A_0\) determined by \(A_0(J_i(0)) = J_i'(0)\) is self adjoint. That is,
\[
g(J_i'(0), J_k(0)) = g(A_0(J_i(0)), J_k(0)) = g(J_i(0), A_0(J_k(0))) = g(J_i(0), J_k'(0)).
\]
for each \(1 \leq i,k \leq n\).
#+END_rem

* Comparison Theory for Riccati Equation

Here we develop a comparison theory for /self adjoint/ solutions to the Riccati equation
\[
A' + A^2 + \operatorname{R}_V = 0.
\]
For our later applications, the restriction to self adjoint solutions will not cause in difficulties.

#+BEGIN_rem
In Eschenburg's notes, the setup is to identify \(T_{\gamma(t)} M\) with \(T_{\gamma(0)} M\) via parallel transport and consider \(A(t)\) as a one-parameter family of endomorphisms of \(T_{\gamma(0)} M\). Explicitly, given \(A(t)\) a solution of the Riccati equation, define
\[
\bar{A}_t (X) = \tau_t^{-1} A(t) \tau_t (X)
\]
for \(X \in T_{\gamma(0)} M\) and where \(\tau_t\) denotes parallel transport from \(\gamma(0)\) to \(\gamma(t)\).

Then \(\bar{A}_t\) is a one-parameter family of endomorphism of \(T_{\gamma(0)} M\) and we may recover \(A\) by
\[
A_t (X) = \tau_t \bar{A} \tau_t^{-1} (X)
\]
for \(X \in T_{\gamma(t)} M\).

The point of this approach is that now \(\bar{A}\) acts on the /finite dimensional/ vector space \(T_{\gamma(0)} M\) rather than the infinite dimensional vector space of vector fields along \(\gamma\).

Equivalently, we could restrict \(A\) to the finite dimensional subspace of parallel vector fields along \(\gamma\). Recall that parallel vector fields are uniquely determined by their initial values at \(T_{\gamma(0)} M\) and hence form an \(n\)-dimensional subspace of all vector fields along \(\gamma\).
#+END_rem

#+BEGIN_rem
We will deviate somewhat from Eschenburg here and make no such restrictions. Since the Jacobi equation and indeed the Riccati equation are tensorial, everything is determined pointwise and there is no need to make the restrictions. At times, as done above we may compute using parallel vector fields (or indeed any vector fields we may find useful) but such a choice is simply for computational convenience. We could work with arbitrary vector fields, but tensorality allows us to choice whatever is convenient at the time.
#+END_rem

Now to the task at hand. In order to compare solutions of the Riccati equation we need an ordering on self-adjoint endomorphisms. The ordering we define is a /partial ordering/ which means that for self adjoint endomorphisms, neither \(T \leq S\) nor \(S \leq T\) need hold in general.

#+BEGIN_defn
Let \(S, T\) be self adjoint endmorphisms acting on a vector space \(E\) with inner product \(g\). We say that \(T \leq S\) provided for every \(X \in E\)
\[
g(T(X), X) \leq g(S(X), X).
\]

Let \(S_t, T_t\) be one parameter families of self-adjoint endomorphisms along \(\gamma\). Then we say \(T \leq S\) provided for every \(t\), \(T_t \leq S_t\).
#+END_defn

Here's the comparison theorem.

#+BEGIN_thm
Let \(R_1, R_2\) be one-parameter families of self-adjoint endomorphisms such that \(R_1 \geq R_2\). Let \(A_i\), \(i = 1,2\) be solutions of the Riccati equation
\[
A_i' + A_i^2 + R_i = 0
\]
with initial conditions satisfying
\[
A_1(0) \leq A_2 (0)
\]
and defined on \([0, t_i)\).

Then
\[
A_1(t) \leq A_2 (t)
\]
for all \(t \in [0, t_1) \cap [0, t_2)\).
#+END_thm

#+BEGIN_rem
Notice that there is a changing of inequality: \(R_1 \geq R_2\) but \(A_1 \leq A_2\). This is just because of the way we have written the Riccati equation: really \(-R_i\) is the driving term which then satisfies \(-R_1 \leq -R_2\). In other words, the assumptions of the theorem are
\[
A_1' + A_1^2 = - R_1 \leq - R_2 = A_2' + A_2^2
\]
and
\[
A_1(0) \leq A_2(0).
\]
And the conclusion is
\[
A_1(t) \leq A_2(t).
\]

The idea of the proof now is to rewrite the inequality as \(A_1' \leq A_2' + A_2^2 - A_1^2\) so that if at some \(t_0\), \(A_1(t_0) = A_2(t_0)\), then \(A_1'(t_0) \leq A_2'(t_0)\). But since \(A_1(0) \leq A_2(0)\), in order that \(A_1(t_0) = A_2(t_0)\), \(A_1\) must increase up to \(A_2\) so that \(A_1'(t_0) \geq A_2' (t_0)\). So we have two opposite inequalities, and if at least one was strict we would obtain a contradiction.

So we must modify the argument to obtain a strict inequality. This is more or less standard but requires a little care.

Also, because the order \(\leq\) on self adjoint endomorphisms is only a partial order, it need not be true that \(A_1(t_0) = A_2(t_0)\); rather we would just find some \(X \in E\) such that \(A_1(t_0) \cdot X = A_2(t_0) \cdot X\). For other elements \(Y \in E\) we could still have \( A_1(t_0) \cdot Y \leq A_2(t_0) \cdot Y\). Thus we also need to account for such possibilities but this is not difficult.
#+END_rem

#+BEGIN_proof
According to the remark, we have
\[
A_1' + A_1^2 \leq A_2' + A_2'
\]
and
\[
A_1(0) \leq A_2(0).
\]

As usual with this type of argument, suppose by way of obtaining a contradiction that the conclusion is false. That is, there exists a \(\tau \in (0, t_1) \cap (0, t_2)\) such that \(A_1(\tau) \not\leq A_2(\tau)\). As mentioned in the remark, \(\leq\) is only a partial order so this does mean that \(A_t(\tau) > A_2(\tau)\). Rather, it means there exists an \(X \in E\) such that
\[
g(A_1(\tau) \cdot X, X) > g (A_2(\tau) \cdot X, X).
\]
Let us define
\[
f(t) = g((A_2(t) - A_1(t)) \cdot X, X)
\]
so that our assumptions give,
\[
f(0) \geq 0, \quad f(\tau) < 0.
\]

Since \(f\) is continuous on \([0, \tau]\), it attains a negative minimum on \([0, \tau]\). Let
\[
m = -\min\{f : 0 \leq t \leq \tau\} > 0
\]
and let \(t_1\) be such that
\[
f(t_1) = -m.
\]
Also by continuity, we may choose \(\lambda > 0\) such that
\[
e^{\lambda \tau} \lambda > \frac{1}{m} \max\{|g((A_1^2(t) - A_2^2)\cdot X, X)| : 0 \leq t \leq \tau\}.
\]

Then we define
\[
h(t) = e^{-\lambda t} f(t) = e^{-\lambda t} g((A_2(t) - A_1(t)) \cdot X, X).
\]
Then the initial inequality \(f(0) \geq 0\) implies \(h(0) \geq 0\) and the contradiction assumption \(f(\tau) < 0\) implies \(h(\tau) < 0\).

By continuity, we may choose \(t_0\) such that
\[
h(t_0) = \min\{h(t) : 0 \leq t \leq \tau\} \leq h(\tau) < 0.
\]
Then at \(t_0\) we have
\[
h'(t_0) \leq 0.
\]
In fact, we will have equality if \(t_0 \ne \tau\) but for our purposes the inequality suffices.

On the other hand, the inequality
\[
A_1' + A_1^2 \leq A_2' + A_2'
\]
implies that
\[
h'(t) = e^{-\lambda t}[g((A_2' - A_1') \cdot X, X) - \lambda g((A_2 - A_1) \cdot X, X)] \geq e^{-\lambda t}[g((A_1^2 - A_2^2) \cdot X, X) - \lambda f(t)].
\]
Now recall that \(m = f(t_1)\) is the infimum of \(f\) while the infimum of \(h(t) = e^{-\lambda t} f(t)\) is attained at \(t_0\). Therefore,
\[
e^{-\lambda t_0}f(t_0) \leq e^{-\lambda t_1} f(t_1) = -m e^{-\lambda t_1}.
\]
That is,
\[
f(t_0) \leq -m e^{-\lambda(t_1 - t_0)} \leq -m e^{-\lambda|(t_1 - t_0)|} \leq -m e^{-\lambda \tau}.
\]
Note that of course we also have \(-m \leq f(t_0)\) but it's the upper bound that is important here.

Therefore at \(t_0\),
\begin{split}
h'(t_0) \geq e^{-\lambda t_0}[g((A_1^2 - A_2^2)(t_0) \cdot X, X) - \lambda f(t_0)] & \geq e^{-\lambda t_0}[g((A_1^2 - A_2^2)(t_0) \cdot X, X) + m \lambda e^{\lambda\tau}] \\
&\geq e^{-\lambda t_0}[-|g((A_1^2 - A_2^2)(t_0) \cdot X, X)| + m \lambda e^{\lambda\tau}] \\
&> 0
\end{split}
with the last inequality by the choice of \(\lambda\). But this contradicts \(h'(t_0) \leq 0\).
#+END_proof

* Comparison Theory for Jacobi Fields
* Averaged Comparison Theory
