#+OPTIONS: toc:nil

#+TITLE: Applications of Comparison Theory

* Jacobi Fields, Conjugate Points and the Exponential Map

Here we see how Jacobi fields arise as variations of the exponential map. This should be of no surprise since Jacobi fields are variations of geodesics and the exponential map is defined in terms of geodesics.

Throughout we will assume that \((M, g)\) is complete so that \((M, d_g)\) is a complete metric space, or equivalently by the Hopf-Rinow theorem, \((M, g)\) is /geodesically complete/ so that \(\exp_x\) is smoothly defined on all of \(T_x M\). In this case, for any \(x, y \in M\) there exists a shortest geodesic joining \(x\) to \(y\). That is, there exists a geodesic \(\gamma : [0, L] \to M\) such that
\[
\gamma(0) = x, \quad \gamma(L) = y, \quad d(x, y) = L(\gamma).
\]
No assumption about uniqueness of \(\gamma\) is made and in general this is false as in the examples below.

Now, let \(x \in M\). We have
\[
\exp_x : T_x M \to M
\]
is a diffeomorphism on an open neighbourhood of the origin. Given \(X, Y \in T_x M\) we think of \(Y \in T_X(T_x M)\) via
\[
\rho_X: Y \in T_x M \mapsto \partial_t|_{t=0} (X + t Y)
\]
which defines a linear isomorphism \(T_x M \to T_X(T_x M)\).

Then we define
\[
d(\exp_x)_X (Y) = \partial_s|_{s=0} \exp_x(X + s Y).
\]
Note that since \(M\) is assumed complete, such an expression is defined.

As to Jacobi fields:

#+BEGIN_defn
Let \(\gamma: [0, L] \to M\) be a geodesic. If there exists a Jacobi field along \(\gamma\) such that \(J(0) = 0\) and \(J(t_0) = 0\) for some \(t_0 \in (0, L]\), then \(y = \gamma(t_0)\) is called a /conjugate/ point of \(x = \gamma(0)\).
#+END_defn

#+BEGIN_lemma
Let \(X, Y \in T_x M\) and let \(\gamma_X\) be the unique geodesic with \(\gamma_X(0) = x\) and \(\gamma_X'(0) = X\). Let \(J(t)\) be the Jacobi field along \(\gamma_X\) with \(J(0) = 0\) and \(J'(0) = Y\). Then
\[
d(\exp_x)_{tX} \cdot tY = J(t).
\]
In particular, \(d(\exp_x)_{tX}\) is singular if and only if the point \(\exp_x(tX)\) is conjugate to \(x\).
#+END_lemma

#+BEGIN_proof
We have
\[
d(\exp_x)_{tX} \cdot tY = \partial_s|_{s=0} \exp_x (tX + s t Y) = \partial_s|_{s=0} \gamma_{X + s Y} (t).
\]
On the other hand,
\[
\gamma_s(t) = \exp_x t(X + sY)
\]
is a geodesic for each hence, hence
\[
J(t) = \partial_s|_{s=0} \gamma_{X + s Y} (t)
\]
is a Jacobi field.

Then
\[
J(0) = \partial_s|_{s=0} \gamma_{X + s Y} (0) = \partial_s|_{s=0} x = 0
\]
and
\[
J'(t) = \partial_t \partial_s|_{s=0} \gamma_{X + sY} (t) = \partial_s|_{s=0} \partial_t \gamma_{X + s Y} = \partial_s|_{s=0} (X + s Y) = Y.
\]

For the last part, \(d(\exp_x)_{tX}\) is singular precisely when it has a non-zero kernel. That is when there exists a non-zero \(Y\) such that
\[
d(\exp_x)_{tX} Y = 0.
\]
Since we know that \(d(\exp_x)_0\) is non-singular we must have \(t > 0\) and taking \(J(0) = 0\), \(J'(0) = \tfrac{1}{t} Y\) we get
\[
J(t) = d(\exp_x)_{tX} (t t^{-1} Y) = 0.
\]
#+END_proof

* Metric Balls and the Cut Locus

#+BEGIN_defn
The open (metric) ball \(B_r(x)\) of radius \(r>0\) and centre \(x \in M\) is the set
\[
B_r(x) = \{y : d(x, y) < r\}.
\]
The closed ball has the inequality replaced by equality.
#+END_defn

Let \(X \in T_x M\) with \(|X| < r\). That is \(X \in B_r(0) \subseteq T_x M\). Then
\[
d(x, \exp_x(X)) \leq L[\gamma_X(1)] = \int_0^1 |\gamma'(t)| dt = \int_0^1 |X| dt = |X| < r.
\]
Thus
\[
\lvert X\rvert < r \Rightarrow \exp_x(X) \in B_r(x).
\]
Conversely, by the Hopf-Rinow theorem, if \(y \in B_r(x)\), there exists a length minimising geodesic \(\gamma\) joining \(x\) to \(y\). Let
\[
X = \frac{d(x, y)}{|\gamma'(0)|} \gamma'(0)
\]
so that
\[
\lvert X\rvert = d(x, y) < r
\]
and hence \(X \in B_r(0)\) such that
\[
\exp_x(X) = \gamma_X(1) = y.
\]
That is
\[
y \in \exp_x(B_r(0)).
\]

Therefore,
\[
B_r(x) = \exp_x(B_r(0)).
\]

In fact, as just observed if \(y \in B_r(x)\), then there exists an \(X \in B_r(0) \subseteq T_x M\) such that \(d(x, y) = L[\gamma_X]\) and \(y = \exp_x(X)\). In other words, \(\gamma_X\) minimises length between \(x\) and \(\gamma_x(t)\) for each \(t \in [0, 1]\): /if there were a shorter geodesic \(\mu\) joining \(x\) to \(\gamma_X(t)\) for some \(t \in (0, 1)\), then following first \(\mu\) from \(x\) to \(\gamma_X(t)\), and then \(\gamma_X\) to \(y\) would give a shorter geodesic joining \(x\) to \(y\).

#+BEGIN_defn
Let,
\[
C_x = \{X \in T_x M : \gamma_X \text{ minimises length for all } t \in [0, 1]\}.
\]
The boundary \(\partial C_x\) is called the /cut locus/ of \(x \in M\). The interior, \(\overset{\circ}{C_x}\) is called the /injectivity domain/.
#+END_defn

Notice that homogeneity of geodesics, \(\gamma_{tX}(s) = \gamma_X (ts)\), if \(X \in C_x\), then so is \(\lambda X\)for all \(\lambda \in [0, 1]\). Thus \(C_x\) is /star shaped/. Moreover, by the Hopf-Rinow theorem, \(M = \exp_x(C_x\).

On the other hand, for \(X \in \overset{\circ}{C_x}\), there does not exist any other \(Y \in \overset{\circ}{C_x}\) such that \(\exp_x(X) = \exp_x(Y)\). This follows since if there is another geodesic \(\mu\) minimising length between \(x\) and \(y = \exp_x(X) = \gamma_X(1)\), then \(\gamma_X\) does not minimise length from \(x\) to \(\gamma_X(1+\epsilon)\) for any \(\epsilon\). The reason for this is that one can prove minimising geodesics are smooth and hence \(mu\) must be parallel or anti-parallel with \(\gamma_X\) at \(y\) so either \(\mu = \gamma_X\), or \(\mu\) meets \(\gamma_X\) coming from the other direction and hence minimises length to \(\gamma_X(1 + \epsilon) = \mu(1-\epsilon)\).

*In other words, \(\exp_x\) is injective on \(\overset{\circ}{C_x}\).*

Now, as in Eschenburg chapter 5 and the references therein, a geodesic \(\gamma\) fails to minimise length from \(x = \gamma(0)\) to \(y = \gamma(1)\) only if either there exists another minimising geodesic joining \(x\) to \(y\) or if \(y\) is a conjugate point to \(x\) along \(\gamma\). We just observed the first possibility and so what remains to prove is that a geodesic does not minimise past a conjugate point (see Eschenburg for the reference to the proof). Thus since \(X \in \overset{\circ}{C_x}\) implies \(\gamma_X\) minimises up to \(1 + \epsilon\) for some \(\epsilon > 0\), neither possibility occurs. Then not only is \(\exp_x\) injective on \(\overset{\circ}{C_x}\) it also is an immersion since \(\d(\exp_x)_X Y = J(t)\) for a Jacobi field along \(\gamma_X\) and since \(\gamma_X\) has no conjugate points \(J(t) \ne 0\) unless \(Y = 0\).

*In other words, \(\exp_x\) is an immersion on \(\overset{\circ}{C_x}\).*

#+BEGIN_rem
Therefore in fact \(\exp_x\) is an injective immersion from \(\overset{\circ}{C_x} \to M\). In fact, it is an embedding and hence \(\exp_x\) is diffeomorphic with it's image. Moreover since \(M = \exp_x C_x\) and \(C_x = \overline{\oveset{\circ}{C_x}}\) is the closure of \(\overset{\circ}{C_x}\).

Therefore \(\exp_x(\overset{\circ}{C_x})\) is a dense, open, contractible subset of \(M\). Since contractible sets have trivial topology, *all* the topology of \(M\) is contained in the boundary \(\partial C_x\)! Another way to put this is that the map \(\exp_x : C_x \to M\) is a surjective map from a topologically trivial set onto \(M\) and thus all the topological information is contained in the map \(\exp_x\) and what's more that information is encoded precisely on the \(\exp_x\) restricted to the boundary. Since the topology of a manifold can be arbitrarily complex, the behaviour of \(\exp_x\) can be arbitrarily bad along the boundary.
#+END_rem

#+BEGIN_rem
We have
\[
B_r(x) = \exp_x(B_r(0) \cap C_x).
\]
This just follows since as discussed above, for any \(y \in M\), there always exists \(X \in C_x\) such that \(\gamma_X\) is length minimising; that is since \(\exp_x : C_x \to M\) is a surjection.
#+END_rem

* Cheng-Bonnet-Myers Diameter Theorem in Positive Curvature

The Bonnet-Myers theorem says that if a complete Riemannian manifold has a positive lower bound, then there is a corresponding upper bound on diameter and hence the manifold is compact. Myers gave the first proof. Prior to that Bonnet proved the statement when the Ricci curvature bound is replaced by the stronger hypothesis that the sectional curvature is bounded. Cheng's contribution was to prove that the equality case is attained precisely on the sphere with it's standard "round" metric.

Let \(k > 0\) and let \(\mathbb{S}^n (k)\) denote the sphere of constant sectional curvature \(k\).

#+BEGIN_thm
Let \((M, g)\) be a Riemannian manifold such that
\[
\operatorname{Ric} \geq (n-1) k = \operatorname{Ric} (\mathbb{S}^n(k))
\]
for some \(k > 0\).

Then
\[
\operatorname{diam} (M, g) := \sup\{d(x, y) : x, y \in M\} \leq \frac{\pi}{\sqrt{k}}.
\]
Moreover, equality is attained if and only if \((M, g)\) is isometric to \(\mathbb{S}^n(k)\).
#+END_thm

#+BEGIN_proof
Let \(\gamma\) be a geodesic with unit length tangent vector \(V = \gamma'\). The assumptions of the theorem imply that
\[
\operatorname{Tr} \operatorname{R}_V = \operatorname{Ric}(V) \geq (n-1) k.
\]
The average comparison theorem for the Riccati equation then implies that for any solution of the Riccati equation, the function \(a = \tfrac{1}{n-1} \operatorname{Tr} A\) satisfies
\[
a(t) \leq \bar{a}(t)
\]
where \(\bar{a}(t)\) satisfies \(a' + a^2 + k = 0\) and \(\bar{a}(0) = a(0)\).

Here we need to take the extended version with \(A(t) \sim 1/t\) as \(t \to 0\) so that our Jacobi fields satisfying \(J(0) = 0\) solve \(J' = A J\).

Then as in the discussion before the average Jacobi field comparison theorem, we take a basis \(\{J_1, \cdots, J_{n-1}\}\) of Jacobi fields solving \(J' = A J\) (equivalently a basis of Jacobi fields such that \(J_i(0) = 0\)). Then by the average Jacobi field comparison theorem, the function \(j = \det (J_1, \cdots, J_{n-1})\) satisfies
\[
|j'| \leq |\bar{j}|
\]
where \(\bar{j}\) is formed from the corresponding fields for \(R = k \operatorname{Id}\) and satisfying \(\bar{j}' = \bar{a} \bar{j}\).

Direct computation verifies that
\[
\bar{a}(t) = \sqrt{k} \cot(\sqrt{k} t)
\]
and
\[
\bar{J}_i(t) = \sin(\sqrt{k} t) e_i
\]
is a linearly independent set of solutions. Therefore, since each \(\bar{J}_i\) has a zero (in fact the first zero) at \(\pi/\sqrt{k}\) we have
\[
\bar{j}(\pi/\sqrt{k}) = 0.
\]
Since \(|j| \leq |\bar{j}|\), there exists a \(t_0 \leq \pi/\sqrt{k}\) with
\[
j(t_0) = 0.
\]
But \(j = \det(J_1, \cdots, J_{n-1})\) and \(J_i\) are a linearly independent set of solutions so that at least one of \(J_i\) must satisfy \(J_i(t_0) = 0\).

Now let \(x, y \in M\) be arbitrary and let \(\gamma\) be a unit length, length minimising geodesic joining \(x\) to \(y\). We have just proven that there is a \(t_0 \leq \pi/\sqrt{k}\) such that \(\gamma(\pi/\sqrt{k})\) is conjugate to \(x\). Since geodesics do not minimise distance past their first conjugate point, we must have
\[
y = \gamma(t_1) \text{ for } t_1 \leq \pi/\sqrt{k}
\]
and
\[
d(x, y) = t_1 \leq \pi/\sqrt{k}.
\]
That is for all \(x, y \in M\),
\[
d(x, y) \leq \pi/\sqrt{k}
\]
and hence
\[
\operatorname{diam} (M, g) \leq \frac{\pi}{\sqrt{k}}.
\]

Note that if we have equality, then there is a geodesic realising the diameter and we must have equality in the average Riccati comparison theorem along that geodesic. This gives \(\operatorname{R}_V = (n-1)k \operatorname{Id}\) along the geodesic. One one needs to show that it in fact, the diameter equality on holds on all geodesics. For this see Eschenburg by applying the maximum principle to certain sub-harmonic functions. 
#+END_proof

#+BEGIN_cor
With the same assumptions as in the theorem, \(M\) is compact and its universal cover is compact hence \(M\) has finite fundamental group.
#+END_cor

#+BEGIN_proof
The theorem implies that both \(M\) and its universal cover \(\hat{M}\) have finite diameter and hence are closed and bounded subsets of themselves. The Hopf-Rinow theorem then implies that both \(M\) and \(\hat{M}\) are compact. The fundamental group is finite, because \(\hat{M} \to M\) is a compact covering hence finite sheeted.
#+END_proof

* Bishop-Gromov Volume Comparison Theorem
