#+OPTIONS: toc:nil

#+TITLE: Geodesics and Exponential Map

* References

- [[http://pabryan.github.io/pdf/teaching/dg/dg.pdf][DG Notes]] Weeks 07 and 08
- Riemannian Geometry: a Modern Introduction by Chavel I.6, I.7
- [[http://myweb.rz.uni-augsburg.de/~eschenbu/comparison.pdf][Comparison Geometry]] by Eschenburg, Section 1.

* Metric Structure

#+BEGIN_defn
The length of a smooth path \(\gamma : [a, b] \to M\) is
\[
L(\gamma) = \int_a^b \sqrt{g_{\gamma(t)}(\gamma'(t), \gamma'(t))} dt.
\]
#+END_defn

Here \(g_x\) is the metric at the point \(x \in M\). If we define
\[
\lvert \gamma' \rvert_g = \sqrt{g_{\gamma(t)}(\gamma'(t), \gamma'(t)})
\]
we may write more briefly
\[
L(\gamma) = \int_a^b |\gamma'| dt
\]
where we dropped the subscript \(g\) because it's tedious to include it every time we write it out! There will usually only be one metric under consideration so this convention won't cause any confusion. If there is more than one metric under consideration, then we will be explicit with subscripts.

#+BEGIN_defn
A metric (i.e. distance function not Riemannian metric!) on \((M, g)\) is given by
\[
d_g (x, y) = \inf\{L(\gamma) : \gamma(0) = x, \gamma(1) = y\}.
\]
#+END_defn

Again, typically we will drop the subscript in \(d_g\) and just write \(d\) except when any confusion might occur.

- The metric topology on \(M\) induced by \(d\) is the same as the manifold topology.

#+BEGIN_defn
The Riemannian manifold \((M, g))\) is /complete/ if the metric space \((M, d)\) is a complete metric space.
#+END_defn

- All our Riemannian manifolds will be complete.

* Geodesics

We'll parametrise our curves over \([0, 1]\) for convenience. Geometric quantities are independent of the parametrisation so this will not result in any loss of generality.

#+BEGIN_defn
A smooth curve \(\gamma : [0, 1] \to M\) is a geodesic if
\[
\nabla_{\gamma'} \gamma' = 0.
\]
#+END_defn

- Geodesics have zero acceleration.
- Equivalently, the velocity vector to a geodesic is /parallel/ along the geodesic.

#+BEGIN_lem
Geodesics have constant speed. That is \(|\gamma'| \equiv \text{const}\).
#+END_lem

#+BEGIN_proof
By metric compatibility we have
\[
\partial_t |\gamma'(t)|^2 = \partial_{\gamma'} g(\gamma', \gamma') = 2 g(\nabla_{\gamma'} \gamma', \gamma') = 0.
\]
#+END_proof

One question might come to mind: do any geodesics exist? If so, how many? What there properties? We'll answer the first two questions here and consider the third question in the next sections.

#+BEGIN_lem
Let \(x \in M\) and \(X \in T_x M\). Then there exists a unique geodesic \(\gamma\) defined on a maximal interval \([0, T)\) such that
\[
\gamma(0) = x, \quad \gamma'(0) = X.
\]
#+END_lem

Here it could be that \(T\) is finite or that \(T = \infty\). The uniqueness here refers to the maximal interval. That is, if \(\sigma\) is a geodesic with \(\sigma(0) = x\) and \(\sigma'(0) = X\) defined on \([0, S)\), then \(S \leq T\) and \(\sigma(t) = \gamma(t)\) for all \(t \in [0, S)\).

The proof is about ODE's on manifolds which are typically done in local coordinates. A coordinate free proof can be given by considering the /geodesic flow/ on the tangent bundle. This is quite an important perspective that we will consider in [[*Exponential Map][Exponential Map]] to obtain smooth dependence on \(x\) and \(X\). I don't know how to produce a coordinate free proof without working on the tangent bundle since the geodesic ODE is a second order system and to turn it into a system of first order ODE's in order to apply local existence and uniqueness theory, one defines variables \(V = \gamma') which is in the tangent bundle. Let me know if there's another way to do it coordinate free!

#+BEGIN_proof
In local coordinates, write \(\gamma(t) = (\gamma^1(t), \dots, \gamma^n(t))\) and
\[
\dot{\gamma} := \partial_t \gamma = \dot{\gamma}^i \partial_i
\]
where the Einstein summation convention is used. Here it's convenient to use a dot rather than a prime to denote derivatives because of the superscripted indices \(i\). Otherwise, it looks rather messy.

Then
\begin{align*}
\nabla_{\dot{\gamma}} \dot{\gamma} &= \partial_{\dot{\gamma}} (\dot{\gamma}^i) \partial_i + \dot{\gamma}^i \nabla_{\dot{\gamma}} \partial_i \\
&= \ddot{\gamma}^i \partial_i + \dot{\gamma}^i \dot{\gamma}^j \nabla_{\partial_j} \partial_i \\
&= \ddot{\gamma}^i \partial_i + \dot{\gamma}^i \dot{\gamma}^j \Gamma_{ij}^k \partial_k.
\end{align*}
where \(\Gamma_{ij}^k = \nabla_{\partial_i} \partial_j\) are the Christoffel symbols of the connection. These are smooth, real valued functions indexed by \(1 \leq i,j,k \leq n\) defined on a coordinate patch /independently of \(\gamma\)/. But keep in mind that they vary from point to point and are evaluated here at \(\gamma(t)\).

Also keep in mind that there are sums here in \(i, j, k\) whenever an index is repeated in a superscript and a subscript. Relabeling the indices (\(i \leftrightarrow k\) in the second sum) and grouping together the coefficients of \(\partial_i\) we get
\[
\nabla_{\dot{\gamma}} \dot{\gamma} = \left(\ddot{\gamma} + \dot{\gamma}^k \dot{\gamma}^j \Gamma_{kj}^i(\gamma^1, \dots, \gamma^n))\right) \partial_i.
\]

Thus \(\gamma = (\gamma^1, \dots, \gamma^n)\) is a geodesic if and only if it satisfies the second order, non-linear system of ODE's
\[
\ddot{\gamma}^i(t) + \Gamma_{kj}^i(\gamma^1(t), \dots, \gamma^n(t)) \dot{\gamma}^k(t) \dot{\gamma}^j(t) = 0.
\]
with \(1 \leq i \leq n\).

The assertion of the lemma is then that given any \(x = (x^1, \cdots, x^n)\) in coordinates and \(X = X^i \partial_i\) there exists a unique solution to the initial value problem
\begin{cases}
\ddot{\gamma}^i + \Gamma_{kj}^i(\gamma^1, \dots, \gamma^n) \dot{\gamma}^k \dot{\gamma}^j &= 0 \\
\gamma^i(0) &= x^i \\
\dot{\gamma}^i (0) &= X^i.
\end{cases}

As a first order system of ODE's obtained by introducing \(V^i = \dot{\gamma}^i\) we have
\begin{cases}
\begin{pmatrix}
\dot{\gamma}^i \\
\dot{V}^i
\end{pmatrix}
&=
\begin{pmatrix}
V^i \\
- \Gamma_{kj}^i(\gamma^1, \dots, \gamma^n) V^k V^j
\end{pmatrix}
\\
\gamma^i(0) &= x^i \\
V^i (0) &= X^i.
\end{cases}

Existence and uniqueness is now guaranteed by the [[https://en.wikipedia.org/wiki/Picard%25E2%2580%2593Lindel%25C3%25B6f_theorem][Picard–Lindelöf theorem]] which states that since the right hand side in parentheses is a smooth function of \(\gamma^i, V^j\) and is in particular Lipschitz, a unique solution exists on a maximal interval \([0, T)\).

One issue is that the solution so obtained is defined in the chart and it may in fact leave the chart whence we can no longer use the inverse chart map to transfer the solution to \(M\). However, we simply use a new chart and existence and uniqueness ensures there exists a unique extension into this chart. Now one uses an open set/continuity argument to complete the details of the proof.
#+END_proof

#+BEGIN_ex
Fill in the details of the open set/continuity argument.
#+END_ex

* Geodesics are Critical Points for the Length Functional

We say that a curve \(\gamma\) is /length minimising/ if
\[
L(\gamma) = d(\gamma(0), \gamma(1)).
\]
That is, the length of \(\gamma\) realises the infimum in the definition of \(d\).

Now is a good time to state a theorem.

#+BEGIN_thm
Suppose \(\gamma\) is length minimising. Then \(\gamma\) is a geodesic. Conversely, every geodesic is locally length minimising in the sense that for all \(t_0 \in [0, 1]\), there is an \(\epsilon > 0\) such that \(\gamma\) restricted to \([0, 1] \cap \{|t - t_0| < \epsilon\}\) is length minimising.
#+END_thm

For now we just give a proof of the first part since it involves calculating variations of curves which will be important later so this is a good opportunity to get accustomed to such variations.

The proof of the second part is more delicate and will be discussed below in [[*Exponential Map][Exponential Map]].

The first part follows immediately from the following:

#+BEGIN_lem
The Euler-Lagrange equation for the length function with fixed end points is precisely the geodesic equation.
#+END_lem

#+BEGIN_proof
A /variation/ of \(\gamma\) is a map
\[
F : [0, 1] \times (-\epsilon, \epsilon) \to M
\]
such that
\[
F(t, 0) = \gamma(t).
\]
We restrict to variations that preserve the end points:
\[
F(0, s) = \gamma(0), \quad F(1, s) = \gamma(1).
\]

Define
\[
\gamma_s(t) = F(t, s).
\]
Then \(\gamma_0 = \gamma\) and \(\gamma_s(0) = \gamma_0(0)\), \(\gamma_s(1) = \gamma_0(1)\).

The curve \(\gamma\) is a /critical point/ for \(L\) among variations with fixed endpoints precisely when
\[
\partial_s|_{s=0} L(\gamma_t) = 0
\]
for all variations with \(\gamma_0 = \gamma\). That is, precisely when /the first variation of \(L\) vanishes at \(s = 0\)/. Now we compute this variation. For notation, let's write
\[
T(s, t) = F_{\ast} \partial_t = \partial_t F (s, t), \quad S(s, t) = F_{\ast} \partial_s = \partial_s F.
\]
Thus is \(T_0(t) := T(0, t) = \gamma'(t)\) is the velocity vector to \(\gamma\) and \(S_0(t) = S(0, t)\) is the variation vector field along \(\gamma\). Note also that \(T_0\) satisfies \(|T_0| = L(\gamma)\) because geodesics are parametrised with constant speed.

Now we compute, using metric compatability
\[
\partial_s|_{s=0} \int_0^1 \sqrt{g(T, T)} dt = \int_0^1 \frac{1}{\sqrt{g(T_0, T_0)}} g(\nabla_S T, T)|_{s=0} dt = \frac{1}{L(\gamma)} \int_0^1 g(\nabla_S T, T)|_{s=0} dt.
\]
Then we commute derivatives using
\[
\nabla_S T - \nabla_T S = [S, T] = [F_{\ast} \partial_s, F_{\ast} \partial_t] = F_{\ast} [\partial_s, \partial_t] = 0
\]
to get
\[
\partial_s L_s|_{s=0} = \frac{1}{L(\gamma)} \int g(\nabla_T S, T)|_{s=0} dt = \frac{1}{L(\gamma)} \int g(\nabla_{T_0} S_0, T_0) dt.
\]

Notice that by commuting derivatives we may evaluate at \(s=0\) because now we are differentiating with respect to \(t\) and not \(s\). Then we use metric compatability once more to move the derivatives off the variation vector
\begin{align*}
\partial_s L_s|_{s=0} &= \frac{1}{L(\gamma)} \int \partial_t [g(S_0, T_0)] dt - g(S_0, \nabla_{T_0} T_0) dt \\
&= g(S_0, T_0)|_{t=0}^1 - \frac{1}{L(\gamma)} \int g(S_0, \nabla_{T_0} T_0) dt.
\end{align*}

But notice that since our variation fixes the endpoints,
\[
S_0(0) = \partial_s|_{s=0} F(0, s) = \partial_s|_{s=0} \gamma(0) = 0
\]
and similarly \(S_0(1) = 0\).

Therefore,
\[
\partial_s L_s|_{s=0} = - \frac{1}{L(\gamma)} \int g(S_0, \nabla_{T_0} T_0) dt.
\]
In other words,
\[
dL_{\gamma} (S_0) = -\frac{1}{L(\gamma)} \int g(\nabla_{T_0} T_0, S_0) dt.
\]

Since \(dL_{\gamma} (S_0) = 0\) for every vector field \(S_0\) along \(\gamma\) with \(S(0) = 0, S(1) = 0\), we find that
\[
\nabla_{\gamma'} \gamma' = \nabla_{T_0} T_0 = 0
\]
and hence \(\gamma\) is a geodesic.
#+END_proof

The first part of the length minimisation theorem - that if a curve \(\gamma\) minimises length then it is a geodesic - follows since then for any variation fixing the endpoints, each \(\gamma_s\) has the same endpoints as \(\gamma\) which minimises length between these points. Thus the function
\[
s \mapsto L_s := L(\gamma_s)
\]
has a local minimum at \(s = 0\) and the first derivative test implies
\[
\partial_s|_{t=0} L_s = 0.
\]
The lemma now applies to conclude that \(\gamma\) is a geodesic.

- A few of the steps above weren't fully justified so here are some exercises to justify them.

First, given a \(\gamma\), variations may be constructed in several ways.

#+BEGIN_ex
Show that there exist variations of \(\gamma\), and in particular that there are variations fixing the endpoints. /Hint/: By the implicit function theorem we can always choose a chart \(\varphi : U \to \mathbb{R}^n\) for \(M\) such that \(\gamma \cap U\) is mapped to a coordinate axis \(x^2 = \cdots = x^n = 0\). Then define a variation of \(\gamma\) in coordinates and transfer back to \(M\) by the inverse of the chart. This produces just a local variation. To get a variation of all \(\gamma\), cover it by charts and patch together the local variations using a partition of unity.
#+END_ex

Recall that a vector field \(V\) along \(\gamma\) is a map \(V : [0, 1] \to TM\) such that \(\pi(V(t)) = \gamma(t)\). Or in other words such that \(V(t) \in T_{\gamma(t)} M\) for each \(t\).

#+BEGIN_ex
Show that for a vector field \(V\) along \(\gamma\) with \(V(0) = 0, V(1) = 0\), if
\[
\int_0^1 g(V(t), S(t)) dt = 0
\]
for every vector field \(S\) along \(\gamma\), then \(V \equiv 0\). /Hint/: Try \(S(t) = \rho(t) V(t)\) where \(\rho : [0, 1] \to \mathbb{R}\).
#+END_ex

#+BEGIN_ex
Show that given a vector field \(S\) along \(\gamma\), there exists a variation of \(\gamma\) with variation field \(S\). /Hint/: You need to define for each \(t\), a curve \(\alpha_t(s)\) such that \(\alpha_t(0) = \gamma(t)\) and \(\alpha_t'(0) = S(t)\). This must be done is such a way that the map
\[
F(t, s) = \alpha_t(s)
\]
depends smoothly on \(t\) and each \(\alpha_t\) is defined for \(s \in (-\epsilon, \epsilon)\) independently of \(t\). Compactness of \(\gamma([0, 1])\) should help here.
#+END_ex

* Exponential Map
* Hopf-Rinow
* Cut Locus
